name: qgi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=2.0
  - scipy=1.11
  - matplotlib=3.7
  - pandas=2.0
  - jupyter
  - sympy=1.12
  - mpmath
  - seaborn
  - pip
  - pip:
    - astropy

